// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using server.Database;

#nullable disable

namespace server.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("server.Models.Bill", b =>
                {
                    b.Property<int>("BillId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("BillId"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<int?>("TopUpId")
                        .HasColumnType("int");

                    b.Property<int?>("TopUpsTopUpId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int?>("TransactionId")
                        .HasColumnType("int");

                    b.HasKey("BillId");

                    b.HasIndex("TopUpsTopUpId");

                    b.HasIndex("TransactionId");

                    b.ToTable("Bills");
                });

            modelBuilder.Entity("server.Models.BillSpecialRechargePackage", b =>
                {
                    b.Property<int>("BillId")
                        .HasColumnType("int");

                    b.Property<int>("SpecialRechargeId")
                        .HasColumnType("int");

                    b.HasKey("BillId", "SpecialRechargeId");

                    b.HasIndex("SpecialRechargeId");

                    b.ToTable("BillSpecialRechargePackages");
                });

            modelBuilder.Entity("server.Models.BillSpecialServicePackage", b =>
                {
                    b.Property<int>("BillId")
                        .HasColumnType("int");

                    b.Property<int>("SpecialServiceId")
                        .HasColumnType("int");

                    b.HasKey("BillId", "SpecialServiceId");

                    b.HasIndex("SpecialServiceId");

                    b.ToTable("BillSpecialServicePackages");
                });

            modelBuilder.Entity("server.Models.Feedback", b =>
                {
                    b.Property<int>("FeedbackId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("FeedbackId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("InitialMessage")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Ratting")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("FeedbackId");

                    b.ToTable("Feedbacks");
                });

            modelBuilder.Entity("server.Models.FeedbackMessage", b =>
                {
                    b.Property<int>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MessageId"));

                    b.Property<int>("FeedbackId")
                        .HasColumnType("int");

                    b.Property<bool>("IsAgent")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("SenderId")
                        .HasColumnType("int");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("MessageId");

                    b.HasIndex("FeedbackId");

                    b.ToTable("FeedbackMessages");
                });

            modelBuilder.Entity("server.Models.SpecialRechargePackage", b =>
                {
                    b.Property<int>("SpecialRechargeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("SpecialRechargeId"));

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("SpecialRechargeName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("SpecialRechargeId");

                    b.ToTable("SpecialRechargePackages");
                });

            modelBuilder.Entity("server.Models.SpecialServicePackage", b =>
                {
                    b.Property<int>("SpecialServiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("SpecialServiceId"));

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("SpecialServiceName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("SpecialServiceId");

                    b.ToTable("SpecialServicePackages");
                });

            modelBuilder.Entity("server.Models.TopUpPackage", b =>
                {
                    b.Property<int>("TopUpId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("TopUpId"));

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("TopUpName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("TopUpId");

                    b.ToTable("TopUpPackages");
                });

            modelBuilder.Entity("server.Models.Transaction", b =>
                {
                    b.Property<int>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("TransactionId"));

                    b.Property<DateTime?>("PaymentDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("TransactionId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("server.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Fullname")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("RefreshTokenExpiredTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("PhoneNumber")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("server.Models.VertifyPhoneData", b =>
                {
                    b.Property<int>("VertifyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("VertifyId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Otp")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("varchar(6)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.HasKey("VertifyId");

                    b.HasIndex("PhoneNumber")
                        .IsUnique();

                    b.ToTable("VertifyPhoneDatas");
                });

            modelBuilder.Entity("server.Models.Bill", b =>
                {
                    b.HasOne("server.Models.TopUpPackage", "TopUps")
                        .WithMany()
                        .HasForeignKey("TopUpsTopUpId");

                    b.HasOne("server.Models.Transaction", "Transaction")
                        .WithMany("Bills")
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("TopUps");

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("server.Models.BillSpecialRechargePackage", b =>
                {
                    b.HasOne("server.Models.Bill", "Bill")
                        .WithMany("BillSpecialRechargePackages")
                        .HasForeignKey("BillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("server.Models.SpecialRechargePackage", "SpecialRechargePackage")
                        .WithMany("BillSpecialRechargePackages")
                        .HasForeignKey("SpecialRechargeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bill");

                    b.Navigation("SpecialRechargePackage");
                });

            modelBuilder.Entity("server.Models.BillSpecialServicePackage", b =>
                {
                    b.HasOne("server.Models.Bill", "Bill")
                        .WithMany("BillSpecialServicePackages")
                        .HasForeignKey("BillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("server.Models.SpecialServicePackage", "SpecialServicePackage")
                        .WithMany("BillSpecialServicePackages")
                        .HasForeignKey("SpecialServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bill");

                    b.Navigation("SpecialServicePackage");
                });

            modelBuilder.Entity("server.Models.FeedbackMessage", b =>
                {
                    b.HasOne("server.Models.Feedback", "Feedback")
                        .WithMany("Messages")
                        .HasForeignKey("FeedbackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Feedback");
                });

            modelBuilder.Entity("server.Models.Bill", b =>
                {
                    b.Navigation("BillSpecialRechargePackages");

                    b.Navigation("BillSpecialServicePackages");
                });

            modelBuilder.Entity("server.Models.Feedback", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("server.Models.SpecialRechargePackage", b =>
                {
                    b.Navigation("BillSpecialRechargePackages");
                });

            modelBuilder.Entity("server.Models.SpecialServicePackage", b =>
                {
                    b.Navigation("BillSpecialServicePackages");
                });

            modelBuilder.Entity("server.Models.Transaction", b =>
                {
                    b.Navigation("Bills");
                });
#pragma warning restore 612, 618
        }
    }
}
